---
extends: default

rules:
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments:
    min-spaces-from-content: 1
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  brackets:
    max-spaces-inside: 1
  braces:
    max-spaces-inside: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
  comments-indentation: disable
  key-ordering: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
